version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db_node_nerocke
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "3173:5432"  # port externe pour PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  node:
    image: ethan/nodejs_postgres:latest  # image Docker Hub buildée
    container_name: nerockenodejs          # nom du conteneur mis à jour
    depends_on:
      - db
    ports:
      - "3001:3000"  # port externe 3001 vers 3000 interne
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV=production
    restart: unless-stopped
    command: ["npm", "run", "start"]  # utiliser start en production

volumes:
  db_data: